// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-backend'
  | 'pref-backend-auto'
  | 'pref-backend-libreoffice'
  | 'pref-backend-word'
  | 'pref-backupBeforeDelete'
  | 'pref-backupBeforeDelete-note'
  | 'pref-backupDirectory'
  | 'pref-backupDirectory-browse'
  | 'pref-backupDirectory-note'
  | 'pref-deleteOriginal'
  | 'pref-deleteOriginal-note'
  | 'pref-description'
  | 'pref-help'
  | 'pref-keywordPattern'
  | 'pref-keywordPattern-note'
  | 'pref-libreOfficePath'
  | 'pref-libreOfficePath-browse'
  | 'pref-restrictByKeywords'
  | 'pref-showNotifications'
  | 'pref-title'
  | 'pref-titleTemplate'
  | 'pref-titleTemplate-note'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
