// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "deleteOriginal": boolean;
      "backupBeforeDelete": boolean;
      "backupDirectory": string;
      "titleTemplate": string;
      "renameMode": string;
      "renamePdfSi": boolean;
      "backend": string;
      "libreOfficePath": string;
      "showNotifications": boolean;
      "restrictByKeywords": boolean;
      "keywordPattern": string;
    };
  }
}
