pref("deleteOriginal", false);
pref("backupBeforeDelete", true);
pref("backupDirectory", "");
pref("titleTemplate", "SI-{{ citationKey }}");
pref("renameMode", "title-only");
pref("renamePdfSi", false);
pref("backend", "__default__");
pref("libreOfficePath", "");
pref("showNotifications", true);
pref("restrictByKeywords", false);
pref("keywordPattern", "si|supplement|supplementary");
